### ISSUE TITLE
Catch PDO exceptions

### ISSUE THREAD

**Issue by nimra98** [lennart-perrey/Desive2#31]
When a PDO exception is thrown, the error message is displayed.
This error message can containt the db credentials, which is a security issue.

"Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for b failed: Name or service not known in /var/www/html/public/DBConnect.php:16 Stack trace: #0 /var/www/html/public/DBConnect.php(16): PDO->__construct('mysql:host=HOSTNAME;DBNAME...', 'USERNAME', 'PASSWORD...') #1 {main} Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for b failed: Name or service not known in /var/www/html/public/DBConnect.php:16 Stack trace: #0 /var/www/html/public/DBConnect.php(16): PDO->__construct('mysql:host=HOSTNAME;DBNAME...', 'USERNAME', 'PASSWORD...') #1 {main} thrown in /var/www/html/public/DBConnect.php on line 16"

**Comment by nimra98** [comment]
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_SILENT);
is not enough. The exceptions should be catched by a try/catch construct:
https://stackoverflow.com/questions/23571128/uncaught-pdoexception-reveals-username-and-password

**Comment by nimra98** [comment]
Catch has been build. Control for all instances.
